### ISSUE TITLE
Cannot read property 'async' of null at module.exports.getProfile

### ISSUE THREAD

**Issue by anantjain-xyz** [mathieudutour/medium-to-own-blog#11]
Here's the terminal output:

```
? Path to the Medium archive /Users/anant/Downloads/medium-export.zip
✔ Parsed Medium content
⠋ Parsing the Medium profile
TypeError: Cannot read property 'async' of null
    at module.exports.getProfile (/Users/anant/.npm/_npx/82554/lib/node_modules/medium-to-own-blog/get-profile.js:9:64)
    at inquirer.prompt.then.then.then.zip (/Users/anant/.npm/_npx/82554/lib/node_modules/medium-to-own-blog/index.js:49:12)
```

**Comment by mathieudutour** [comment]
hum weird 🤔 
If you unzip the medium-export.zip, do you have a `profile/profile.html` file inside?

**Comment by anantjain-xyz** [comment]
Hey! Sorry about this. This is what happened:
1. I downloaded my Medium .zip file using Safari.
2. Safari unzipped the download automatically.
3. I used the Mac's "Compress..." option to make a .zip again.
4. This zip caused the error above.

I re-downloaded the .zip file using Chrome so that it stays zipped. Sure enough, it worked fine this time around. Closing this issue.
