### ISSUE TITLE
`publicUrl` points to localhost:8000 on the Discuss on Twitter Link

### ISSUE THREAD

**Issue by harshattray** [mathieudutour/medium-to-own-blog#12]
The Discuss on Twitter link which takes in the href `https://twitter.com/search?q=${publicUrl}` , the `publicUrl`  points to localhost:8000.
![Screenshot 2019-06-01 at 3 55 19 AM](https://user-images.githubusercontent.com/3311805/58738103-02120280-8422-11e9-89c6-fb9ec53dbbb5.png)

**Comment by mathieudutour** [comment]
Yep, you need to change the public URL in the `gatsby-config.js`. I need to write docs about it

**Comment by mathieudutour** [comment]
We could perhaps add a prompt to enter the public url after the netlify steps. Then we can modify the gatsby-config automatically and create a new commit.

**Comment by mathieudutour** [comment]
fixed in https://github.com/mathieudutour/medium-to-own-blog/commit/1f612695a5f20aeee65634a24345e43ebdda2a3f
