### ISSUE TITLE
Question: does the blog have a CMS/way to create new posts?

### ISSUE THREAD

**Issue by crisdosaygo** [mathieudutour/medium-to-own-blog#22]

**Comment by clathrop** [comment]
Would also like to know the answer to this

**Comment by paramaggarwal** [comment]
The recommended approach to creating posts is using the GitHub website and the New File button - which also offers a Preview mode for Markdown. (needs to be documented)

I want to try integrating [Netlify CMS](https://www.netlifycms.org) but worried it might complicate the initial migration process.

**Comment by mathieudutour** [comment]
I need to write some docs about it but the short answer is:
- create a new folder in the `content` folder. The name of the folder will be the url of the post.
- inside the newly created folder, create a `index.md` file.

Inside the file, you can specify some metadata for the post using the frontmatter syntax:
```md
---
title: "Title of the article"
description: "a short description that will show up in the front page of the blog and in the google description"
date: "date of the publication, you can leave empty until you publish it"
categories:
  - tag
  - of
  - the 
  - article
published: `true` or `false` (if false, you can access the article via its url but it won't show up in the front page)
---
```

and after the `---`, you can write any markdown
