### ISSUE TITLE
Migrate Gist Support

### ISSUE THREAD

**Issue by NetanelBasal** [mathieudutour/medium-to-own-blog#25]
Thanks for this great tool. Each one of my blog posts contains code blocks which linked to a gist. There is a way to migrate them?

Thanks.

**Comment by vesper8** [comment]
it would probably be helpful to link to one such blog post so the author can see how feasible adding that feature is

**Comment by NetanelBasal** [comment]
http://netbasal.com

**Comment by mathieudutour** [comment]
Ah I was just working on that. Should be working with 0.1.10

Let me know if that works for you

**Comment by notrab** [comment]
I just ran this and the gists weren't copied over. Happy to help where I can!

Output: https://notrab.netlify.com/getting-started-with-create-react-app-redux-react-router-and-redux-thunk/
Input: https://medium.com/@notrab/getting-started-with-create-react-app-redux-react-router-redux-thunk-d6a19259f71f

**Comment by mathieudutour** [comment]
Hum weird, I'll try to have a look

**Comment by dbarochiya** [comment]
Even I am having the same issue 

Input: https://hackernoon.com/automate-deployment-of-projects-to-github-pages-using-travis-ci-5f13b918f029

Output : https://dbarochiya.netlify.com/automate-deployment-of-projects-to-github-pages-using-travis-ci/

**Comment by mathieudutour** [comment]
@notrab Found the issue. The script was getting confused when gists have a caption. I'll publish the updated version soon

@dbarochiya There doesn't seem to be any gists on your article?
