### ISSUE TITLE
Unknown field 'categories'

### ISSUE THREAD

**Issue by alexohneander** [mathieudutour/medium-to-own-blog#28]
**Describe the bug**
If I want to puplicate the data with netifly, the categories can not be imported

**Screenshots**
`9:46:07 AM: success update schema — 0.041 s
9:46:08 AM: error GraphQL Error Encountered 2 error(s):
9:46:08 AM: - Unknown field 'categories' on type 'MdxFrontmatter'. Source: document `BlogIndex` file: `GraphQL request`
9:46:08 AM:   GraphQL request (15:11)
9:46:08 AM:   14:           description
9:46:08 AM:   15:           categories
9:46:08 AM:                 ^
9:46:08 AM:   16:           date(formatString: "MMMM DD, YYYY")
9:46:08 AM: - Unknown field 'categories' on type 'MdxFrontmatter'.
9:46:08 AM:       file: /opt/build/repo/src/templates/blog-post.js
9:46:08 AM: Skipping functions preparation step: no functions directory set
9:46:08 AM: Caching artifacts`

**Comment by crutchcorn** [comment]
I'm wondering if this occurs because it tries to pull data that isn't present in the frontmatter that's generated. 

Potentially opting out of the type inference might help here? 

https://www.gatsbyjs.org/docs/schema-customization/#opting-out-of-type-inference

**Comment by mathieudutour** [comment]
Probably yes. But at soon as there is at least one post with categories, it should infer it. So I’m guessing all the posts are drafts?

**Comment by mathieudutour** [comment]
Fixed in https://github.com/mathieudutour/medium-to-own-blog/commit/5b05894dea07e34ddacc39dfd08417f79fa648f8
