### ISSUE TITLE
Cannot create directory, name too long.

### ISSUE THREAD

**Issue by artiya4u** [mathieudutour/medium-to-own-blog#29]
**Describe the bug**
It cannot create a directory from the URL encoded Thai language with long URL.
Maybe need to decode URL first.

**Expected behavior**
- What's the URL of the Medium article it is failing to parse? 
https://medium.com/@artiya4u/%E0%B9%81%E0%B8%97%E0%B8%99%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%88%E0%B8%B0%E0%B8%A3%E0%B8%B1%E0%B8%99-ethereum-mainnet-%E0%B8%AB%E0%B8%A3%E0%B8%B7%E0%B8%AD-testnet-%E0%B9%80%E0%B8%AD%E0%B8%87-%E0%B9%83%E0%B8%AB%E0%B9%89%E0%B8%A5%E0%B8%AD%E0%B8%87%E0%B9%84%E0%B8%9B%E0%B8%95%E0%B9%88%E0%B8%AD%E0%B8%81%E0%B8%B1%E0%B8%9A%E0%B9%82%E0%B8%AB%E0%B8%99%E0%B8%94%E0%B8%82%E0%B8%AD%E0%B8%87-infura-%E0%B8%94%E0%B8%B9%E0%B8%84%E0%B8%A3%E0%B8%B1%E0%B8%9A-f9f4737f8727
- What part of the article isn't parsed correctly?
It cannot create a directory from my language with long URL.

**Screenshots**
![parse](https://user-images.githubusercontent.com/3830524/58764270-5981b100-858f-11e9-8886-fbd8932a61c6.png)

**Comment by mathieudutour** [comment]
Oh very sorry about that. Should be fixed in https://github.com/mathieudutour/medium-to-own-blog/commit/646354a02343c40f6467e2538b98e806d2b79fe6
