### ISSUE TITLE
Medium posts don't necessarily have tags

### ISSUE THREAD

**Issue by JiRadu** [mathieudutour/medium-to-own-blog#36]
**Describe the bug**

**To Reproduce**
1. Go to https://github.com/JiRadu/test-blog2
2. Link your netlify to it
3. Try to deploy

**Expected behavior**
I expect the build to succeed

**Screenshots**
<img width="1680" alt="Screenshot 2019-06-03 at 20 39 19" src="https://user-images.githubusercontent.com/13013122/58822405-12072d80-8640-11e9-970b-62d0e140eaa8.png">
I get this error

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Firefox
 - Version 67

**Comment by mathieudutour** [comment]
Hum, looks like you don't have any blog post?

**Comment by JiRadu** [comment]
I did check now and I previously made a test post that i published. The posts folder of the archive does have 1 item in it

**Comment by mathieudutour** [comment]
If you don't mind, could you paste the file here (or perhaps send it to me privately) ?

**Comment by JiRadu** [comment]
[medium-export.zip](https://github.com/mathieudutour/medium-to-own-blog/files/3248948/medium-export.zip)

**Comment by mathieudutour** [comment]
ok so it's because none of the posts have any tags. I didn't think it was possible. I'll check how to distinguish a comment from a post if tags are not a solution then!

**Comment by JiRadu** [comment]
[medium-export.zip](https://github.com/mathieudutour/medium-to-own-blog/files/3248954/medium-export.zip)

I deleted the profile and ips folders for privacy

**Comment by JiRadu** [comment]
ok, so, as you advised i tagged the posts, and start again, and it works if the posts have tags 👍 
The issue remain, but this can be a good topic if anyone has this problem until the fix is released
Thank you for your VERY quick response, keep up the good work!

**Comment by mathieudutour** [comment]
should be fixed in https://github.com/mathieudutour/medium-to-own-blog/commit/4bd4bd20125db26ddf26fa533201aa561aa40d80
