### ISSUE TITLE
script to import a single article

### ISSUE THREAD

**Issue by koryteg** [mathieudutour/medium-to-own-blog#39]
It would be nice to be able to add a single exported article with something like: `npm run import-article`. would you be interested in this?
looks like you could just do a bit of refactoring on the `getMarkdownFromPost` function to get it to run as a stand alone command.

**Comment by mathieudutour** [comment]
That sounds interesting yes :+1:
Perhaps accepting the URL of the article as an argument?

**Comment by mathieudutour** [comment]
Fixed! The created project now have an npm script to import an article (`npx --package=medium-to-own-blog import-medium-article`)
