### ISSUE TITLE
Adding the medium-like editor to create new posts

### ISSUE THREAD

**Issue by dbarochiya** [mathieudutour/medium-to-own-blog#40]
I have noticed that all the medium articles will be converted to markdown before uploading to the repository and one should create a markdown file to create a new article. 

I think with the use of [this](https://yabwe.github.io/medium-editor/) medium-like open source editor this process can be done easily. 

There is a [project](https://ionicabizau.github.io/medium-editor-markdown/example/) which is made on top of the above project which converts the editor output to markdown syntax in real-time. On a temporary basis, a new article link can be created which leads to [this editor](https://ionicabizau.github.io/medium-editor-markdown/example/).

**Comment by mathieudutour** [comment]
So what would you recommend? Happy to accept a PR to improve the docs. The PR could perhaps mention that tool indeed

**Comment by dbarochiya** [comment]
If there is any way to commit to git repository directly from the website then we can integrate the editor into the app itself. But I guess this project is for the people who are already familiar with the concepts for git & markdown.

For now - a simple edit script would be fine which performs these steps 
* Prompts for the title, tags, etc.
* Redirects to the medium-to-markdown editor
https://ionicabizau.github.io/medium-editor-markdown/example/
* Prompts for the generated markdown
* Creates a commit & merge to master

**Comment by dbarochiya** [comment]
> So what would you recommend? Happy to accept a PR to improve the docs. The PR could perhaps mention that tool indeed

I have added the tool link in the docs. Have a look #42

**Comment by mathieudutour** [comment]
It'd be super nice to create a webapp with:
- login with GitHub
- select a repo
- find the articles from the repo
- select an article or create a new one
- show the medium-like editor
- create a new branch/commit/PR on save

But I don't think I'll time to work on time :smile:

**Comment by dbarochiya** [comment]
Yes, anyhow this project is for the **developers-cum-bloggers**. All we can do for others is to write a great doc on how to dive into the world of git & markdowns 😆. 

I think it would be great to have a landing page for this project which shows the demo & steps for the stuff like 
* create a blog 
* add/edit articles
* add analytics to the blog 

I am also busy with work as I just joined my first company, I would love to contribute to this project based on the bandwidth I will get !!

**Comment by mathieudutour** [comment]
That'd be awesome!

**Comment by dbarochiya** [comment]
Yeah, Let me know after you decide in which direction to procced with the landing page 

Closing this Issue for now

**Comment by dbarochiya** [comment]
Yeah, Let me know after you decide in which direction to procced with the landing page 

Closing this Issue for now
