### ISSUE TITLE
Investigate netlify CMS

### ISSUE THREAD

**Issue by mathieudutour** [mathieudutour/medium-to-own-blog#44]
https://www.netlifycms.org/docs/gatsby/

Could be a good alternative to https://ionicabizau.github.io/medium-editor-markdown and is pretty much everything I described here: https://github.com/mathieudutour/medium-to-own-blog/issues/40#issuecomment-500214629.

But before we can safely integrate it, we need https://github.com/netlify/netlify-cms/issues/1472 to be fixed.

**Comment by paramaggarwal** [comment]
I have been working on this. I have it setup at https://blog.paramaggarwal.com/admin/ - will begin raising PRs for the same now that I have become comfortable with how to get it to work.

This also involved changing the way static assets are stored (in a dedicated separate directory).

Config: https://github.com/paramaggarwal/blog/blob/master/static/admin/config.yml

<img width="1440" alt="Screenshot 2019-06-16 at 10 31 55 am" src="https://user-images.githubusercontent.com/543981/59559324-06ddd580-9022-11e9-919b-b0174be1225c.png">
<img width="1440" alt="Screenshot 2019-06-16 at 10 32 05 am" src="https://user-images.githubusercontent.com/543981/59559333-4efcf800-9022-11e9-9d14-cb6121cd2ddc.png">

**Comment by mathieudutour** [comment]
> This also involved changing the way static assets are stored (in a dedicated separate directory).

Yes that’s the issue linked and I really don’t want to store all the assets in a separate directory, I think it’s a mistake from an architecture POV. From the issue, it looks like it’s going to be solve soon-ish so I’m tempted to wait for it before making to many changes

**Comment by paramaggarwal** [comment]
https://github.com/netlify/netlify-cms/issues/1472 and https://github.com/netlify/netlify-cms/pull/2958 are merged now. This change is now possible without changing the way images are stored.

**Comment by mathieudutour** [comment]
I have it done locally. Will push a new version soon

**Comment by paramaggarwal** [comment]
Wow, this will completely breathe fresh life into this project! It will finally solve the problem of creating content using a GUI.

**Comment by mathieudutour** [comment]
fixed in the new version
