### ISSUE TITLE
npx medium-to-own-blog not generate blog, generate import article

### ISSUE THREAD

**Issue by diomalta** [mathieudutour/medium-to-own-blog#45]
Time to use npx medium-to-own-blog shows the option of importing a single article.
Download and install project I can run the correct script through the node and generate the blog

**Comment by mathieudutour** [comment]
I think we found an `npx` bug. I just published a workaround for now, it should work

**Comment by dbarochiya** [comment]
Actually even I faced this same issue but running the following command lead to the desired output
`npx --package=medium-to-own-blog medium-to-own-blog`

(I don't know why it is though :P)

**Comment by mathieudutour** [comment]
I think it should be fixed with the latest version? `npx medium-to-own-blog@0.2.2`

**Comment by diomalta** [comment]
yes, resolved the error.
