### ISSUE TITLE
Deploy error in netifly duplicate code variable in code-highlighting

### ISSUE THREAD

**Issue by diomalta** [mathieudutour/medium-to-own-blog#46]
Error deploy in netifly with component code-highlighting

![image](https://user-images.githubusercontent.com/22456325/59190768-f3c79300-8b53-11e9-8341-788b67a0ebd0.png)

Because for two variables with same name.

![image](https://user-images.githubusercontent.com/22456325/59191251-5ff6c680-8b55-11e9-85f6-10cdd4a080b0.png)

**Comment by mathieudutour** [comment]
:scream: not sure how I missed that! Should be fixed now
