### ISSUE TITLE
Medium import fails if the user has no profile picture

### ISSUE THREAD

**Issue by mpaktiti** [mathieudutour/medium-to-own-blog#47]
**Describe the bug**
The `Parse the Medium profile` step fails if the user has no profile photo set at Medium. 
I didn't have one and when I run this I got the error:
```
TypeError: Cannot read property 'attributes' of null
    at module.exports.getProfile (/Users/mariap/.npm/_npx/81974/lib/node_modules/medium-to-own-blog/lib/get-profile.js:40:5)
```

I checked the [line of code that failed](https://github.com/mathieudutour/medium-to-own-blog/blob/master/lib/get-profile.js#L40) and realized what might be the case. I set a profile photo in my Medium account, re-exported my info, and the step was executed successfully.

**Expected behavior**
Not sure, maybe failing is what you wanna do in this case, but even so you can throw a more specific error (or use a generic avatar that the user can later change). 

**Screenshots**
The error I got:
<img width="572" alt="Screenshot 2019-06-10 19 51 09" src="https://user-images.githubusercontent.com/11715799/59211992-f066f280-8bb9-11e9-90f6-a1bef234d9af.png">

**Comment by mpaktiti** [comment]
Thanks for building this tool btw, it's pretty cool :)

**Comment by mathieudutour** [comment]
Ah yes, there is already a default avatar, we should just use that
