### ISSUE TITLE
Error during build both locally and on Netlify

### ISSUE THREAD

**Issue by akeller** [mathieudutour/medium-to-own-blog#48]
**Describe the bug**
Fails to build and deploy on Netlify and fails build locally.

Error when building locally
`ValidationError: child "siteMetadata" fails because [child "siteUrl" fails 
error The site's gatsby-config.js failed validation`

**To Reproduce**
Deploy on Netlify to see build fails, or npm run-script build to see error message from above section.

**Expected behavior**
I assume this build script should run with no errors and deploy just works with no additional changes.

**Screenshots**
Here is a screenshot from the Netlify build, error message isn't super helpful looking

![image](https://user-images.githubusercontent.com/1051363/59293686-551b5f00-8c45-11e9-9846-ff7bdfea8502.png)

**Desktop (please complete the following information):**
 - OS: Mojave 
 - Browser: Chrome
 - Version: 74.0.3729.169

**Additional context**
I'm new to Netlify and Gatsby so I'm hoping I didn't miss something small. I have a brand new Netlify account and I'm using a custom domain. Or trying to :)

**Comment by mathieudutour** [comment]
If you look in your config.js file, the `siteUrl` is `amara.dev` which isn't a proper url. It should be `https://amara.dev`. 

I could probably prefix the url automatically if the protocol is missing. I'll have a look

**Comment by akeller** [comment]
Thanks I knew it was something small! I was looking at the wrong config file, or rather the gatsby-config file. 

Build failed with another issue, but it looks like that has something to do with something in my content. I'll open another issue if I can't figure it out.
