### ISSUE TITLE
Doesn't import all articles from https://medium.com/@tomayac

### ISSUE THREAD

**Issue by tomayac** [mathieudutour/medium-to-own-blog#49]
🙏 First of all, thanks a ton for creating this tool! It's great! 👏

**Describe the bug**
When I run the import script multiple times, randomly articles from my archive are being skipped.

**Expected behavior**
- A clear and concise description of what you expected to happen.
All articles should get converted.

- What's the URL of the Medium article it is failing to parse? 
It randomly skips some. Here's a [link to my archive](https://drive.google.com/file/d/1qUMnCog-efmcx7evdLEOk7GVfOPE7gUz/view?usp=sharing_eil&ts=5d00b7d9) (@mathieudutour, please request access).

- What part of the article isn't parsed correctly?
N/A, there is no clear pattern. It might be a time-out?

**Screenshots**
- If applicable, add screenshots to help explain your problem.
N/A.

**Comment by mathieudutour** [comment]
the script skips the responses to other articles. I just tried the import with your archive and indeed, one article is missing: https://medium.com/dev-channel/experimenting-with-the-wake-lock-api-b6f42e0a089f. Do you have others missing?

I'll try to see why

**Comment by tomayac** [comment]
Thanks so much for looking into this. It seems to randomly vary, sometimes the mentioned article is included, sometimes it isn't, sometimes it produces only five articles, sometimes more… It's really weird.

**Comment by mathieudutour** [comment]
Oh I think I know why, and I don't like it.

 It seems that Medium is changing its frontend code and all the css classes are minified :/ It doesn't seem to be deployed everywhere yet so depending on which A/B test path you take, you get the normal classes or the minified ones.

**Comment by mathieudutour** [comment]
should be fixed in 0.3.0
