### ISSUE TITLE
Markdown in image caption did not get parsed

### ISSUE THREAD

**Issue by paramaggarwal** [mathieudutour/medium-to-own-blog#5]
**Describe the bug**

Markdown in the image caption did not convert to HTML. 

Input: https://medium.com/@paramaggarwal/how-to-be-right-by-being-wrong-9fd26dca20b3
Output: https://blog.paramaggarwal.com/How-to-be-Right-by-Being-Wrong/

**Screenshots**
<img width="707" alt="Screenshot 2019-06-01 at 12 19 23 AM" src="https://user-images.githubusercontent.com/543981/58727802-f531e680-8402-11e9-8a32-b333912e68c5.png">

**Comment by mathieudutour** [comment]
It's a bug in `gatsby-remark-images`. I'll see if they are interested in accepting a PR to fix it
