### ISSUE TITLE
The script gets stuck at `⠋ Parsing the Medium posts [5/23]`

### ISSUE THREAD

**Issue by vfonic** [mathieudutour/medium-to-own-blog#50]
**Describe the bug**

It's been stuck on `⠋ Parsing the Medium posts [5/23]` for quite some time now. Any easy way to debug it?

It's using ~20% of CPU, but there's no progress as of about 10min now.

**Comment by mathieudutour** [comment]
Hum it's probably downloading some gifs or images. Do you have an article with a lot of gifs perhaps?

**Comment by vfonic** [comment]
I was on a slow internet connection earlier, indeed. I don't have many photos, but maybe some photo failed to download. Not sure if that would keep the script running in loop?

I just re-run the command now and it passed that step relatively quickly (I'm on a good internet connection now).

🤷‍♂ I guess I'll close this issue then.
