### ISSUE TITLE
Netlify build fails (Plugin gatsby-mdx returned an error)

### ISSUE THREAD

**Issue by vfonic** [mathieudutour/medium-to-own-blog#51]
I noticed that this is accessible to public, so here's the build log: https://app.netlify.com/sites/vfonic-blog/deploys/5d00fd43b5a0d50009a94637

Here's the GH repo: https://github.com/vfonic/blog

One thing I specified differently, I allowed Netlify to access only vfonic/blog repository. It can not access any other (private) repositories.

What am I missing?

**Desktop (please complete the following information):**
 - OS: macOS 10.14.5 (18F203)

**Comment by mathieudutour** [comment]
it's because a tag isn't escaped: https://github.com/vfonic/blog/pull/1

**Comment by vfonic** [comment]
Ahhhh! Thanks for all the time you put into finding this!

When I saw the error message mentioning `todos`, I figured it might be some boilerplate or similar in your package's code. It didn't even occur to me that it might be the content of my blog posts.

I'll try again, but this time I'll read the error message more carefully. :)

**Comment by vfonic** [comment]
> 12:53:22 AM: Site is live

🎉 

Thank you!
This is amazing! Thank you for building this!

https://vfonic-blog.netlify.com/
