### ISSUE TITLE
Bad "Discuss on twitter" link on the demo website

### ISSUE THREAD

**Issue by doliG** [mathieudutour/medium-to-own-blog#52]
**Describe the bug**

**To Reproduce**
1. Go to 'https://mathieudutour-blog.netlify.com/Design-engineers/'
2. Scroll down until the end of the page
3. Click on 'Discuss on Twitter'
4. See error : 'No results for http://localhost:8000/Design-engineers/'

**Expected behavior**
I don't really understand what you want to do, but I'm sure localhost should not be here

**Comment by paramaggarwal** [comment]
Should be fixed with 1f612695a5f20aeee65634a24345e43ebdda2a3f - this is because of missing `siteUrl`. For your existing site, please update this in `config.js`.

**Comment by mathieudutour** [comment]
fixed
