### ISSUE TITLE
after parsing i did not show any if my publish blog, it only extract draft stories in content folder,

### ISSUE THREAD

**Issue by parthvadhadiya** [mathieudutour/medium-to-own-blog#57]
**Describe the bug**
after passing url of medium export. it went through all my article in console, but if i look into content folder after extraction i did not see any of my publish blogs, only my draft saved on medium is there.  and after deploy using netlify, i only end up seeing empty page with profile name and image.

**Comment by dbarochiya** [comment]
Hey, Can you provide more details? ( screenshots, article link, etc.)

**Comment by parthvadhadiya** [comment]
medium ling - https://medium.com/@parthvadhadiya424
github link - https://github.com/parthvadhadiya/my-pen
netlify link - https://elated-kilby-1eaee6.netlify.com/

**Comment by VishalBheda** [comment]
same issue

netlify link- https://lucid-jennings-5d3462.netlify.com/


**Deploy log**
4:33:06 PM: Build ready to start
4:33:08 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
4:33:08 PM: build-image tag: v3.3.2
4:33:08 PM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
4:33:08 PM: Fetching cached dependencies
4:33:08 PM: Failed to fetch cache, continuing with build
4:33:08 PM: Starting to prepare the repo for build
4:33:09 PM: No cached dependencies found. Cloning fresh repo
4:33:09 PM: git clone https://github.com/VishalBheda/vishalbheda72-blog
4:33:09 PM: Preparing Git Reference refs/heads/master
4:33:10 PM: Found netlify.toml. Overriding site configuration
4:33:10 PM: Starting build script
4:33:10 PM: Installing dependencies
4:33:11 PM: Downloading and installing node v10.16.0...
4:33:12 PM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
4:33:12 PM: #
4:33:12 PM:                                    2.6%
4:33:12 PM: 
##########
4:33:12 PM:  13.9%
4:33:13 PM: 
#############
4:33:13 PM:                 18.7%
4:33:13 PM: 
############################################
4:33:13 PM:                      62.3%
4:33:13 PM: 
##########################################
4:33:13 PM: ######################          89.2%
4:33:13 PM: 
############################################################
4:33:13 PM: ############ 100.0%
4:33:13 PM: Computing checksum with sha256sum
4:33:13 PM: Checksums matched!
4:33:16 PM: Now using node v10.16.0 (npm v6.9.0)
4:33:16 PM: Attempting ruby version 2.6.2, read from environment
4:33:17 PM: Using ruby version 2.6.2
4:33:18 PM: Using PHP version 5.6
4:33:18 PM: Started restoring cached node modules
4:33:18 PM: Finished restoring cached node modules
4:33:18 PM: Installing NPM modules using NPM version 6.9.0
4:33:21 PM: npm
4:33:21 PM:  WARN deprecated @hapi/joi@14.5.0: This version is no longer maintained
4:33:21 PM: npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
4:33:21 PM: npm WARN deprecated package has been deprecated in favor of directly
4:33:21 PM: npm WARN
4:33:21 PM: deprecated including core-js/stable (to polyfill ECMAScript
4:33:21 PM: npm WARN deprecated features) and regenerator-runtime/runtime
4:33:21 PM: npm WARN deprecated (needed to use transpiled generator functions):
4:33:21 PM: npm WARN deprecated
4:33:21 PM: npm WARN deprecated   > import "core-js/stable";
4:33:21 PM: npm WARN deprecated   > import "regenerator-runtime/runtime";
4:33:24 PM: npm
4:33:24 PM: WARN deprecated joi@11.4.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
4:33:28 PM: npm WARN
4:33:28 PM: deprecated hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
4:33:28 PM: npm WARN deprecated topo@2.0.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
4:33:31 PM: npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
4:34:10 PM: > sharp@0.22.1 install /opt/build/repo/node_modules/sharp
4:34:10 PM: > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
4:34:11 PM: info
4:34:11 PM: sharp
4:34:11 PM:  Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
4:34:16 PM: > pre-commit@1.2.2 install /opt/build/repo/node_modules/pre-commit
4:34:16 PM: > node install.js
4:34:16 PM: > core-js@2.6.9 postinstall /opt/build/repo/node_modules/core-js
4:34:16 PM: > node scripts/postinstall || echo "ignore"
4:34:16 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
4:34:16 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
4:34:16 PM: > https://opencollective.com/core-js 
4:34:16 PM: > https://www.patreon.com/zloirock 
4:34:16 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
4:34:16 PM: > core-js-pure@3.1.4 postinstall /opt/build/repo/node_modules/core-js-pure
4:34:16 PM: > node scripts/postinstall || echo "ignore"
4:34:16 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
4:34:16 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
4:34:16 PM: > https://opencollective.com/core-js 
4:34:16 PM: > https://www.patreon.com/zloirock 
4:34:16 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
4:34:17 PM: > spawn-sync@1.0.15 postinstall /opt/build/repo/node_modules/spawn-sync
4:34:17 PM: > node postinstall
4:34:17 PM: > gatsby-telemetry@1.1.2 postinstall /opt/build/repo/node_modules/gatsby-telemetry
4:34:17 PM: > node src/postinstall.js
4:34:17 PM: > cwebp-bin@5.1.0 postinstall /opt/build/repo/node_modules/cwebp-bin
4:34:17 PM: > node lib/install.js
4:34:17 PM:   ✔ cwebp pre-build test passed successfully
4:34:17 PM: > mozjpeg@6.0.1 postinstall /opt/build/repo/node_modules/mozjpeg
4:34:17 PM: > node lib/install.js
4:34:18 PM:   ✔ mozjpeg pre-build test passed successfully
4:34:18 PM: > pngquant-bin@5.0.2 postinstall /opt/build/repo/node_modules/pngquant-bin
4:34:18 PM: > node lib/install.js
4:34:18 PM:   ✔ pngquant pre-build test passed successfully
4:34:21 PM: npm
4:34:21 PM:  notice created a lockfile as package-lock.json. You should commit this file.
4:34:21 PM: npm WARN
4:34:21 PM:  eslint-config-react-app@3.0.8 requires a peer of babel-eslint@9.x but none is installed. You must install peer dependencies yourself.
4:34:21 PM: npm WARN
4:34:21 PM:  ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
4:34:21 PM: npm WARN optional
4:34:21 PM:  SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
4:34:21 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
4:34:21 PM: added 2056 packages from 1122 contributors and audited 31879 packages in 61.481s
4:34:21 PM: found 0 vulnerabilities
4:34:21 PM: NPM modules installed
4:34:23 PM: Started restoring cached go cache
4:34:23 PM: Finished restoring cached go cache
4:34:23 PM: unset GOOS;
4:34:23 PM: unset GOARCH;
4:34:23 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
4:34:23 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
4:34:23 PM: go version >&2;
4:34:23 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
4:34:23 PM: go version go1.12 linux/amd64
4:34:23 PM: Installing missing commands
4:34:23 PM: Verify run directory
4:34:23 PM: Executing user command: gatsby build
4:34:26 PM: success open and validate gatsby-configs — 0.015
4:34:27 PM: success load plugins — 1.182
4:34:27 PM: success onPreInit — 0.007
4:34:27 PM: success delete html and css files from previous builds — 0.011
4:34:27 PM: success initialize cache — 0.008
4:34:27 PM: success copy gatsby files — 0.024
4:34:27 PM: success onPreBootstrap — 0.019
4:34:28 PM: success source and transform nodes — 0.931
4:34:28 PM: success building schema — 0.333
4:34:28 PM: success createPages — 0.043
4:34:28 PM: success createPagesStatefully — 0.046
4:34:28 PM: success onPreExtractQueries — 0.003
4:34:28 PM: success update schema — 0.034
4:34:28 PM: success extract queries from components — 0.171
4:34:28 PM: success write out requires — 0.004
4:34:28 PM: success write out redirect data — 0.001
4:34:29 PM: success Build manifest and related icons — 0.107
4:34:29 PM: success onPostBootstrap — 0.109
4:34:29 PM: info bootstrap finished - 5.764 s
4:34:29 PM:                  The requested width "150px" for a resolutions field for
4:34:29 PM:                  the file /opt/build/repo/src/images/avatar.png
4:34:29 PM:                  was larger than the actual image width of 50px!
4:34:29 PM:                  If possible, replace the current image with a larger one.
4:34:29 PM: success Generating image thumbnails — 2/2 - 0.137 s
4:34:29 PM: success run static queries — 0.166 — 3/3 18.19 queries/second
4:34:49 PM: success Building production JavaScript and CSS bundles — 19.985
4:34:49 PM: success Rewriting compilation hashes — 0.001
4:34:49 PM: success run page queries — 0.323 — 4/4 12.44 queries/second
4:34:52 PM: success Building static HTML for pages — 2.940 — 4/4 10.81 pages/second
4:34:52 PM: info Done building in 29.423 sec
4:34:52 PM: Skipping functions preparation step: no functions directory set
4:34:52 PM: Caching artifacts
4:34:52 PM: Started saving node modules
4:34:52 PM: Finished saving node modules
4:34:52 PM: Started saving pip cache
4:34:53 PM: Finished saving pip cache
4:34:53 PM: Started saving emacs cask dependencies
4:34:53 PM: Finished saving emacs cask dependencies
4:34:53 PM: Started saving maven dependencies
4:34:53 PM: Finished saving maven dependencies
4:34:53 PM: Started saving boot dependencies
4:34:53 PM: Finished saving boot dependencies
4:34:53 PM: Started saving go dependencies
4:34:53 PM: Finished saving go dependencies
4:34:55 PM: Build script success
4:34:55 PM: Starting to deploy site from 'public'
4:34:55 PM: Creating deploy tree 
4:34:56 PM: 3 new files to upload
4:34:56 PM: 0 new functions to upload
4:34:57 PM: Starting post processing
4:34:57 PM: Post processing done
4:34:58 PM: Site is live
4:35:22 PM: Finished processing build request in 2m14.476451514s

**Comment by splisson-altair** [comment]
same, only draft posts were extracted to content folder

**Comment by mathieudutour** [comment]
I think it's the same issue as https://github.com/mathieudutour/medium-to-own-blog/issues/49

**Comment by chris-pearce** [comment]
I'm getting the same issue, tried it three times, and every time only drafts are extracted.

**Comment by mathieudutour** [comment]
should be fixed in 0.3.0
