### ISSUE TITLE
Adding a git ssh:// link fails the Edit on GitHub link

### ISSUE THREAD

**Issue by paramaggarwal** [mathieudutour/medium-to-own-blog#6]
**Describe the bug**

Generated link: https://blog.paramaggarwal.com/How-to-be-Right-by-Being-Wrong/git@github.com:paramaggarwal/blog.git/edit/master/content/How-to-be-Right-by-Being-Wrong/index.mdx

Expected link: https://github.com/paramaggarwal/blog/edit/master/content/How-to-be-Right-by-Being-Wrong/index.mdx

**Screenshots**
<img width="478" alt="Screenshot 2019-06-01 at 12 21 41 AM" src="https://user-images.githubusercontent.com/543981/58727899-3b874580-8403-11e9-9f45-88a9b6dae706.png">

**Comment by mathieudutour** [comment]
Ah did you enter `git@github.com:paramaggarwal/blog.git` when asked for the url of the repo? Should have been `https://github.com/paramaggarwal/blog`

You can change it in the `gatsby-config.js`

**Comment by paramaggarwal** [comment]
Yes, because I use SSH key as my auth. If I would have added the HTTPS link, then it would have asked me for my username/password.

**Comment by mathieudutour** [comment]
indeed. Maybe we can check if the user enters a url starting with `git@` and transform it into a proper github url

**Comment by paramaggarwal** [comment]
Yeah, might be too much complexity for the tool though. We can choose to ignore this corner case.

**Comment by mathieudutour** [comment]
wasn't too hard: https://github.com/mathieudutour/medium-to-own-blog/commit/6c1594dc1966f504b3306063b1da611f730c5bf7
