### ISSUE TITLE
Why  project is not uploading

### ISSUE THREAD

**Issue by ayush-srivasta** [mathieudutour/medium-to-own-blog#76]
Successfully created project 'QuizApp' on GitHub, but initial commit failed: *** Please tell me who you are. Run git config --global user.email "you@example.com" git config --global user.name "Your Name" to set your account's default identity. Omit --global to set the identity only in this repository. unable to auto-detect email address (got 'Ayush Srivastav@LAPTOP-CS29LAIK.(none)')

**Comment by mathieudutour** [comment]
as stated in the error, you need to setup git:
```
git config --global user.email "you@example.com" 
git config --global user.name "Your Name"
```
