### ISSUE TITLE
Page title is always "Mathieu Dutour - Blog"

### ISSUE THREAD

**Issue by paramaggarwal** [mathieudutour/medium-to-own-blog#8]
Due to this line:

https://github.com/mathieudutour/medium-to-own-blog/blob/647fcbb7db76a5b7bbcbe8f40b02d7e4c41fe642/gatsby-template/src/pages/index.js#L15

(I am not sure how to fix this, hence can't raise a PR.)

**Comment by mathieudutour** [comment]
Ah yep, just noticed that as well. Here is the fix: https://github.com/mathieudutour/medium-to-own-blog/commit/d994d6dbef3de6323a0d19bdde488cd198948de5
