### ISSUE TITLE
Longer tags break styling

### ISSUE THREAD

**Issue by paramaggarwal** [mathieudutour/medium-to-own-blog#9]
Minor issue, just adding this here to track it. ([from](https://blog.paramaggarwal.com/Neural-Network-Tuning-with-TensorFlow/))

<img width="785" alt="Screenshot 2019-06-01 at 12 47 18 AM" src="https://user-images.githubusercontent.com/543981/58729351-d6cdea00-8406-11e9-91cb-b04534900caf.png">

**Comment by mathieudutour** [comment]
This should fix it: https://github.com/mathieudutour/medium-to-own-blog/commit/b2eb68a820d737e0607725b977b9bdfd796dcc8f
